<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="muji-pc" name="com.lemon.cases.RechargeCase" tests="5" failures="1" timestamp="16 四月 2020 12:49:25 GMT" time="1.041" errors="0">
  <testcase name="test" time="0.089" classname="com.lemon.cases.RechargeCase"/>
  <testcase name="test" time="0.101" classname="com.lemon.cases.RechargeCase"/>
  <testcase name="test" time="0.123" classname="com.lemon.cases.RechargeCase"/>
  <testcase name="test" time="0.108" classname="com.lemon.cases.RechargeCase"/>
  <testcase name="test" time="0.620" classname="com.lemon.cases.RechargeCase">
    <failure type="java.lang.AssertionError" message="expected [断言成功] but found [期望值：{&quot;code&quot;:0,&quot;msg&quot;:&quot;OK&quot;,&quot;data&quot;:{&quot;id&quot;:631,&quot;leave_amount&quot;:56750.0,&quot;mobile_phone&quot;:&quot;18900000000&quot;,&quot;reg_name&quot;:&quot;hehe&quot;,&quot;reg_time&quot;:&quot;2019-10-20 21:46:06.0&quot;,&quot;type&quot;:1},&quot;copyright&quot;:&quot;Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved&quot;}不在响应体内。]">
      <![CDATA[java.lang.AssertionError: expected [断言成功] but found [期望值：{"code":0,"msg":"OK","data":{"id":631,"leave_amount":56750.0,"mobile_phone":"18900000000","reg_name":"hehe","reg_time":"2019-10-20 21:46:06.0","type":1},"copyright":"Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved"}不在响应体内。]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.RechargeCase.test(RechargeCase.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- com.lemon.cases.RechargeCase -->
